version: "3.9"
services:
   web:
    # Берем Dockerfile из каталога app
    build: ./APP
     # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./APP/:/usr/src/APP/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
   db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:15.3-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      # Учетные данные, которые можно будет переопределить
      - ./.env.dev

volumes:
  postgres_volume:
